### ISSUE TITLE
Determine which platforms architectures we want to support with qcluster

### ISSUE THREAD

**Issue by cdoconno** [QsonLabs/qcluster#4]
#### Question

We have not yet made a decision on what platforms we want qcluster to support. Initially I would like to include the build tests for the following operations systems:

- linux
- mac osx
- windows

If we encounter issues with an operating system prior to distributing version 1.0.0 build, we can consider removing support entirely for macosx or windows, or managing feature sets for each.

**Comment by cdoconno** [comment]
@AaronLionsheep -- any issues you see with trying to initially support across all platforms? I created a new branch in [initial-distribution](QsonLabs/qcluster/tree/initial-distribution) that I will use to start getting our build and deployment setup in line. I'll work to publish a 0.0.1 regardless of whether it works or not in order to get the pipeline in place

**Comment by AaronLionsheep** [comment]
@cdoconno My initial thoughts are to leverage GitHub Actions to run tox (flake8 and unit tests) with a platform matrix. We can also leverage artifact generation to help with publishing.

**Comment by AaronLionsheep** [comment]
So far, testing has been done on MacOS, but there are no platform-specific libraries used.

asyncio is built into Python and should work regardless of the platform.
aiohttp appears to be tested on Windows, MacOS, and Linux.

**Comment by cdoconno** [comment]
Great closing this and will track with #5
