### ISSUE TITLE
Determine which platform we will use for publishing packages

### ISSUE THREAD

**Issue by cdoconno** [QsonLabs/qcluster#6]
#### Issue

We have decided to use GitHub Actions for the CI/CD pipeline for building qcluster. GitHub also has GitHub Packages which can be used as a package registry. My inclination is to host packages only on **PyPI** with the `qsonlabs` account to ensure that the package can be installed without contacting GitHub. 

It may be feasible in the future to  leverage GitHub Packages when the following GitHub roadmap issue fir [Packages to support pip via PyPI](https://github.com/github/roadmap/issues/94) is complete

We will publish via `twine` as part of the github actions using an API key

**Comment by cdoconno** [comment]
@AaronLionsheep -- any other considerations with hosting on PyPI you'd like to consider before I get going on this?

**Comment by AaronLionsheep** [comment]
@cdoconno PyPI seems like the way to go at the moment to be able to install directly with pip.

**Comment by cdoconno** [comment]
Great closing this and will track with #5
